stages:
  - build
  - test
  - bench

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
    - gpu, a100
  script:
    - cmake -S . -B build -DCMAKE_CUDA_ARCHITECTURES=80-real -DPHANTOM_ENABLE_TEST=ON -DPHANTOM_ENABLE_BENCH=ON -DPHANTOM_ENABLE_PYTHON_BINDING=ON
    - cmake --build build -j
  artifacts:
    paths:
      - build/bin
      - build/lib

test BFV:
  stage: test
  tags:
    - gpu, a100
  script:
    - ./build/bin/example_context 1
  dependencies:
    - build

test BGV:
  stage: test
  tags:
    - gpu, a100
  script:
    - ./build/bin/example_context 2
  dependencies:
    - build

test CKKS:
  stage: test
  tags:
    - gpu, a100
  script:
    - ./build/bin/example_context 3
  dependencies:
    - build

bench BFV:
  stage: bench
  tags:
    - gpu, a100
  script:
    - ./build/bin/bfv_bench
  dependencies:
    - build

bench BGV:
  stage: bench
  tags:
    - gpu, a100
  script:
    - ./build/bin/bgv_bench
  dependencies:
    - build

bench CKKS:
  stage: bench
  tags:
    - gpu, a100
  script:
    - ./build/bin/ckks_bench
  dependencies:
    - build

bench NTT:
  stage: bench
  tags:
    - gpu, a100
  script:
    - ./build/bin/ntt_bench
  dependencies:
    - build

bench KeySwitch:
  stage: bench
  tags:
    - gpu, a100
  script:
    - ./build/bin/keyswitch_bench
  dependencies:
    - build
